### ISSUE TITLE
File name structure configurable

### ISSUE THREAD

**Issue by lauraluiz** [KarelCemus/play-i18n#10]
I couldn't find any strong reason why it is being used the file structure "name.yaml.lang" instead of "name.lang.yaml". The current structure makes it more difficult for applications to recognize it is a YAML file.

What are the main advantages of the chosen structure? Can it be considered to change the structure somehow (e.g. by overriding code, configuration)?

**Comment by KarelCemus** [comment]
Hi, I designed this library long time ago and this was probably my poor judgment, I believe. And as there is probably nobody else using this library, there was no need to change it. I can look at it on the weekend.

**Comment by KarelCemus** [comment]
Released `1.1.0`
