### ISSUE TITLE
MessagesApi was already configured

### ISSUE THREAD

**Issue by svenporto** [KarelCemus/play-i18n#12]
When 

```
libraryDependencies ++= Seq(
  // YAML localization module
  "com.github.karelcemus" %% "play-i18n" % "1.1.1"
)
```

is added, I receive this error. I'm using Play `2.6.10.`

```
Unexpected exception
CreationException: Unable to create injector, see the following errors:

1) A binding to play.api.i18n.MessagesApi was already configured at play.api.i18n.I18nModule.bindings(I18nModule.scala:14):
Binding(interface play.api.i18n.MessagesApi to ProviderConstructionTarget(class play.api.i18n.DefaultMessagesApiProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
  at play.ext.i18n.MultiFormatMessagesModule.bindings(MultiFormatMessagesModule.scala:52):
Binding(interface play.api.i18n.MessagesApi to ConstructionTarget(class play.ext.i18n.MultiFormatMessagesApi)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
```

**Comment by KarelCemus** [comment]
That's odd. The `I18nModule` is disabled by [reference.conf](https://github.com/KarelCemus/play-i18n/blob/master/src/main/resources/reference.conf#L17) of this project, see it yourself.

Probably something overrides the config in your project.

Try adding the following line into your configuration, it should help

```hocon
play.modules.disabled += "play.api.i18n.I18nModule"
```

**Comment by KarelCemus** [comment]
Obviously disabling the module inside another module is not supported:

> Note: If you are working on a library, it is highly discouraged to use play.modules.disabled to disable modules, as it can lead to nondeterministic results when modules are loaded by the application (see this issue for reasons on why you should not touch play.modules.disabled). In fact, play.modules.disabled is intended for end users to be able to override what modules are enabled by default.

**Comment by KarelCemus** [comment]
Documentation adjusted.

**Comment by svenporto** [comment]
Indeed, that one did it for me 🙌
