### ISSUE TITLE
i18next support

### ISSUE THREAD

**Issue by Enalmada** [KarelCemus/play-i18n#13]
I believe that play supporting a standardized message format that backend and frontend share is going to be an increasing demand.  YAML is certainly an improvement over message files and [i18next](https://www.i18next.com/) format could be the next evolution of that concept:
- comprehensive [support](https://www.i18next.com/overview/supported-frameworks).  This would allow play to seamlessly power the api of any modern frontend. 
- potential for managing keys through a service like [locize](https://locize.com) or [PhraseApp](https://phraseapp.com/docs/guides/formats/i18next/) and export one format for both client and server rather than two formats (play/yaml for server, i18next for client)
- java support through the [android api](https://github.com/i18next/i18next-android).  I believe play-i18n could extend this and get standardized client/server support for [features](https://github.com/i18next/i18next-android#options) like plural for free.

(The competition seems to be the [icu format](http://userguide.icu-project.org/formatparse/messages) used by [formatjs](https://formatjs.io/) but that format seems very painful to work with but I have no experience with it so I could be wrong.  I only am leaning i18next right now due to comprehensive support above.)

How do you feel about play-i18n supporting i18next format and api?  
To start, I will probably just convert my play message files into i18next format at build time since I think I can pull that off without much issue.  It just isn't the endgame so I wanted to throw this out for your thoughts.

**Comment by KarelCemus** [comment]
How would you imagine that? The intention of play-i18n is to provide an alternative implementation to Play's Messages API. I'm not familiar with i18next, but I peeked at it and it seems like much more complex solution comparing to MessagesAPI, so I guess it wouldn't fit to the API. It looks more like an alternative API instead of an alternative implementation.

Speaking of managing services, it seems to me like the library would have to implement some kind of DAO and public API, which seems to be far beyond the intended scope of this library.

Am I right or I am missing something? I admit I took just a brief peek. However, it seems to me like a proposal of a novel library instead of an evolution of this.

Anyway, thank you for your contribution and proposition of an interesting idea.

**Comment by Enalmada** [comment]
I love that you have provided yaml as an alternative to .properties and I think conditionally supporting additional alternatives could complement the awesome core work you have done.  I think that conditionally supporting `play.i18n.formats.json`, `play.i18n.formats.i18next`, `play.i18n.formats.icu` might make more sense than forking play-i18n to do a play-i18next module since they share the same core need of disabling the default messaging module for a custom implementation and this module has. 

The raw format of the i18next message format appears to just be [json](https://www.i18next.com/misc/json-format).  Conceptually it seems to call for a period in a key to trigger nested lookup of value just like yaml format.  Json has become the standard when it comes to modern client frameworks so i18next format is probably the closest format to yaml that a full stack play framework developer is going to get.  

I notice that i18next has some [java](https://github.com/i18next/i18next-android) code support (its targeted to android but i suspect it would work in play but I could be wrong).  I think it could be sufficient to leverage that maven dependency to power the lookup of the key/value from a local i18next json file in the same way you do now for yaml file so that it would just be an alternative implementation.  

Update: Interesting to note that if I just put a i18next json file called "messages.yaml.en" into my conf directory it already works because yaml is actually a superset of json (i did not know that till just now).   So....perhaps play-i18n already supports i18next enough that the play server and javascript client of choice can share the same files and just documentation is needed to make potential play users aware of this. 

I do think I notice an issue I would like your advice on: 
messages.[lang] is merged over messages.yaml.en. I would expert yaml to take priority over the older original properties file if both are in classpath.  Obviously not an issue for 99% of people who are just going to have one on the other but I am curious what you think should be merged over the other.

**Comment by KarelCemus** [comment]
I understand your point, but still, I believe that power of i18next is way out of Play's Messages API. 

I agree that support of json would be correct. That is just another format. But both icu and i18next have additional features such as plurals etc., which is beyond the limitations of the current API. Therefore, play-i18n would either support only reduced subset of features or introduce a novel API, which I'm not much sure about.

> So....perhaps play-i18n already supports i18next enough that the play server and javascript client of choice can share the same files and just documentation is needed to make potential play users aware of this.

That is interesting though not tested solution. I believe there should be some tests first before I could publically claim that it is officially supported.

> messages.[lang] is merged over messages.yaml.en. I would expert yaml to take priority over the older original properties file if both are in classpath. Obviously not an issue for 99% of people who are just going to have one on the other but I am curious what you think should be merged over the other.

As you guessed, it was intended to have either one or the other, I cannot imagine why would you have both. Can you tell me your use case, please?

And regarding i18next, ... I don't have much time and as I won't use it, then I have to apologize not to implement it myself. However, I am willing to merge it and supervise it (if necessary). Are you willing to make a PR?

**Comment by Enalmada** [comment]
I think that play messages API might be made minimally compatible with i18next with some creative coding. Because messages api takes in arbitrary parameters, I think it could look for the second parameter starting with some command prefix like "i18next_" so you could look for something like `messages("key", "i18next_plural", 1)` which would map to `i18n.t("key", new Operation.Plural(1))`.  Just thinking aloud though.  Unfortunately even the i18next android (java) client doesn't even support some of the [additional features](https://github.com/i18next/i18next-android#multiple-plural-forms) so I think it could be fine if some minimal play support didn't either.     

I am just ending the google searching phase to figure out what is best practice and what other people are doing with play server / javascript client.  Just the fact that play-i18n handles json as is means that it might be good enough initially for my needs (most of my key use is moving client side and I think I can continue to call "key" vs "key_plural" manually using messages api server side where i just send some emails).   Another thing I am evaluating conceptually is [play-jsmessages](https://github.com/julienrf/play-jsmessages) which converts play messages to json.    

About the yaml vs properties priority, there really is no good reason to have both, I just happened to convert a .properties file to yaml in my conf to poke around with i18n and noticed that it wasn't picking up my yaml file like I expected.  This problem is only likely to mildly impact new users who are silly enough to migrate to yaml without removing original properties during an initial evaluation phase. 

No worries about not having the time to implement...the open source community is in your debt for the contributions and ongoing maintenance you already do (I love play-redis).  I appreciate your willingness to let me chew on how to do play with i18next client a bit with you and willingness to supervise/merge a future PR.    I am going to dig into all the options a bit more and will be back with more understanding soon.

**Comment by KarelCemus** [comment]
>  I am evaluating conceptually is play-jsmessages which converts play messages to json.

I can recommend it, I've been using it for several years and works like a charm. Though I'm not sure, maybe I customized it a bit but the concept is the same.

> About the yaml vs properties priority

Alright then, what do you propose? Should YAML go over property files? If so, why? I perceive them as equal, and as long as there exists a warning that you have a conflict here, it is fine with me, but I am not sure that such a warning exists.

> messages("key", "i18next_plural", 1) which would map to i18n.t("key", new Operation.Plural(1))

I don't think this is a good approach. Scala is intended to by type-safe and checked at compile time but
this would lead to tons of typos and possibly runtime issues. Furthermore, it does not seem much intuitive to me. Either you don't use i18next and then you do not care about it at all, or you use it and then it seems like big overhead to me. I believe there should exist some advanced API supporting plurals etc. and an adapter implementing Play's API, which is basically the same concept, which is used by play-redis. However, it seems to me like a lot of work and I'm not quite sure it is worth it.

Maybe some implicit conversions would be better, something like `messages.plural(1)("key", 1)`

**Comment by Enalmada** [comment]
In theory, since the average user is going to be using this project to go from .properties to yaml,  I would expect yaml to take priority.  In reality, I think a note in the how to use section of the documentation explaining that .properties takes priority could be helpful to new users thinking they can just pop in some yaml in their existing conf dir just to poke around with i18n when properties files still exists.  

Yes, the mapping suggestion is indeed a "suboptimal" approach for the reasons you pointed out.  I think it could be made a bit safer by providing some utility function to be passed to messages : `messages("key", util.i18next_plural(1))`.  It is no doubt trying to force a round peg into a square hole.  I might be better off abandoning messages completely and just using the android/java i18next client with some scala wrapper.    

I am going to see how far I can get with play-jsmessages and possibly using this repo as is to let play read i18next json files and will report back.
