### ISSUE TITLE
Play 2.8 support

### ISSUE THREAD

**Issue by aljchristensen** [KarelCemus/play-i18n#22]
Similar to #16, I'm running into issues migrating from Play 2.7 to 2.8. I'm encountering the error below:

```
CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void play.api.i18n.DefaultMessagesApi.<init>(scala.collection.immutable.Map, play.api.i18n.Langs, java.lang.String, boolean, boolean, scala.Option, play.api.http.HttpConfiguration)'
  at play.ext.i18n.MultiFormatMessagesApi.<init>(MultiFormatMessagesModule.scala:16)
  at play.ext.i18n.MultiFormatMessagesApi.class(MultiFormatMessagesModule.scala:16)
  while locating play.ext.i18n.MultiFormatMessagesApi
  while locating play.api.i18n.MessagesApi
    for the 1st parameter of play.i18n.MessagesApi.<init>(MessagesApi.java:32)
  at play.ext.i18n.MultiFormatMessagesModule.bindings(MultiFormatMessagesModule.scala:53):
Binding(class play.i18n.MessagesApi to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.i18n.MessagesApi
...
```

Do you plan to support Play 2.8? Thank you!

**Comment by KarelCemus** [comment]
I wasn't but I can. I didn't know that somebody actually uses this library. I will look at it probably today and see what I can do

**Comment by KarelCemus** [comment]
Released version `2.1.0`, should be in maven repos in a couple of hours. Are you willing to test it and give me some feedback? I slightly revamped the provider of `MessagesApi` so I hope it works

**Comment by aljchristensen** [comment]
As far as I can tell, everything seems to be working as expected with the new release. Thanks so much for taking a look at this so quickly.

**Comment by KarelCemus** [comment]
Happy to hear, thanks for the feedback

**Comment by kgaurav-livongo** [comment]
@KarelCemus - can you please direct me to the version with the fix?

**Comment by Krishnag09** [comment]
Hi @KarelCemus i am using 2.8.16 and still seeing this issue
`[info]   java.lang.NoSuchMethodError: 'void play.api.i18n.DefaultMessagesApi.<init>(scala.collection.immutable.Map, play.api.i18n.Langs, java.lang.String, boolean, boolean, scala.Option, play.api.http.HttpConfiguration)'
`
could you please direct me to the version with the fix.

**Comment by KarelCemus** [comment]
Which version of `play-i18n` are you using? Btw it is more convenient if you can provide the full stacktrace or at least the significant part of it, since errors without any context cannot be debugged or reproduced

**Comment by kgaurav-livongo** [comment]
I don't have a dependency defined for play-118n. Here is trace
`[info]   java.lang.NoSuchMethodError: 'void play.api.i18n.DefaultMessagesApi.<init>(scala.collection.immutable.Map, play.api.i18n.Langs, java.lang.String, boolean, boolean, scala.Option, play.api.http.HttpConfiguration)'
[info]   at com.livongo.play.common.util.test.playHelpers$.defaultControllerComponents(playHelpers.scala:183)
[info]   at controllers.GraphQLControllerTest$TestEnv.createGqlController(GraphQLControllerTest.scala:415)
[info]   at controllers.GraphQLControllerTest$TestEnv.<init>(GraphQLControllerTest.scala:379)
`

**Comment by Krishnag09** [comment]
Thanks for replying. I don't have a dependency defined for play-118n. Here is trace
`[info]   java.lang.NoSuchMethodError: 'void play.api.i18n.DefaultMessagesApi.<init>(scala.collection.immutable.Map, play.api.i18n.Langs, java.lang.String, boolean, boolean, scala.Option, play.api.http.HttpConfiguration)' [info]   at com.xx.xxx.xxx.util.test.playHelpers$.defaultControllerComponents(playHelpers.scala:183) [info]   at controllers.GraphQLControllerTest$TestEnv.createGqlController(GraphQLControllerTest.scala:415) [info]   at controllers.GraphQLControllerTest$TestEnv.<init>(GraphQLControllerTest.scala:379) `

**Comment by KarelCemus** [comment]
If you don't use have a dependency on `play-i18n` then you don't have an error related to this library :-) The name of this lib is a bit unfortunate but this is not the official play-i18n dependency, this is a custom implementation. Therefore it is not wired to your project

Your code at `com.xx.xxx.xxx.util.test.playHelpers$.defaultControllerComponents(playHelpers.scala:183)` is complied against a different/old version of play, I guess
